### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by ahartikainen** [grburgess/stan_utility#5]
Hi,

I think there could be some further improvements for the utility.

Use `gzip` to compress pickle streams.

    import gzip

    with gzip.open("...") as f:
        pickle.dump(model, f)

Also, I added some performance improvement suggestions to https://github.com/betanalpha/jupyter_case_studies/issues/4 but they are not critical. I understand if you don't want to add them to this package.

# precision when printing
In prints use formatter to control the number of digits (e.g. 2)

    "{:.2f}%".format(n/N)

(edit. today depending on the wanted support, this could use fstrings)

# _by_chain -function (also see the next subject)
equals to

    numpy.swapaxes(ef, 0, 1)

# reshaping extract
lines 48 and 49

    ef = _by_chain(ef)
    ef = ef.reshape(-1, len(ef[0][0]))

equals to

    ef = ef.reshape(-1, ef.shape[-1], order='F')

# line 53
no need to call extract()

    fit.extract().keys() == fit.sim['pars_oi']

# line 56
should this line save the result?

    shaped[param_name] = shaped[param_name].reshape(*([-1] + dim))

**Comment by ahartikainen** [comment]
Also you are already using ArviZ, which means you could probably use the `az.ess` and `az.rhat` to calculate the rank based estimations. (You can insert numpy arrays with `(chain,draw,*shape)` order, which can be done with `numpy.swapaxes(arr, 0, 1)`

**Comment by grburgess** [comment]
Hi! Thanks! I'm actually considering (and have been using for a bit) Arviz package completely as I have been using cmdstanpy lately for the reduce_sum function. The main point of this originally was to have the original utility in Betancourt's case study and have the ability to store the fits to HDF5. 

ArviZ accomplishes these two things in a compact way and I'm curious if further development is really warranted. I have some issues with the netcdf format... but it may be better to focus attention with PRs there rather than here.

Opinions @ahartikainen ?

**Comment by ahartikainen** [comment]
Yes, if there are problems with netcdf, create issue in arviz and let's fix that.

**Comment by grburgess** [comment]
Well, issues might be a strong word, but extracting flatten chains would be a nice thing... and I haven't figured that out yet. 

So, I'm probably moth-balling this repo and focusing there. If you agree, I'll close the issue.

**Comment by ahartikainen** [comment]
We have stack method. Add issue for this (we had discussion about it this week and I think we will add some examples how to do that.
